---
title: Working At It
date: 2018-08-23
---
author: bcw768
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just trying to learn Github!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
